<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite1439b8710c695a73c7c237fab32be01
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite1439b8710c695a73c7c237fab32be01::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite1439b8710c695a73c7c237fab32be01::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInite1439b8710c695a73c7c237fab32be01::$classMap;

        }, null, ClassLoader::class);
    }
}
